# source("~/Documents/ETS_PCA/Plot-Scripts/Vary_Covariance_Structure.R")
# source("~/Documents/ETS_PCA/Plot-Scripts/Vary_Error_Variance.R")
# source("~/Documents/ETS_PCA/Plot-Scripts/Vary_Proportion_Validated.R")
source("~/Documents/ETS_PCA/Plot-Scripts/All_Barbell.R")
source("~/Documents/ETS_PCA/Plot-Scripts/All_Bar.R")
source("~/Documents/ETS_PCA/Plot-Scripts/sharedY.R")
